# -*- coding: utf-8 -*-
"""LetsUpgrade1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1srqIaNrdJbXt4WeihWFma6W9dMaJuM6B
"""

print("Input integers:") 
nums = list(map(int, input().split()))
nums.sort() 
nums.reverse() 
print("After sorting the said integers:") 
print(*nums)